#!/bin/sh

set -e

cleanup() {
    docker-compose -f test/stack.yml down -v
}
trap cleanup EXIT

if [ "$1" = "build" ]
then
    shift
    docker-compose -f test/stack.yml build --pull "$@"
fi
docker-compose -f test/stack.yml run --rm -T grace
